version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.dgcaoffice.example.com:
    container_name: peer0.dgcaoffice.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.dgcaoffice.example.com
      - CORE_PEER_ADDRESS=peer0.dgcaoffice.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.dgcaoffice.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.dgcaoffice.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dgcaoffice.example.com:7051
      - CORE_PEER_LOCALMSPID=DGCAOfficeMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dgcaoffice.example.com/peers/peer0.dgcaoffice.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/dgcaoffice.example.com/peers/peer0.dgcaoffice.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.dgcaoffice.example.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.regionaloffice.example.com:
    container_name: peer0.regionaloffice.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.regionaloffice.example.com
      - CORE_PEER_ADDRESS=peer0.regionaloffice.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.regionaloffice.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.regionaloffice.example.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.regionaloffice.example.com:9051
      - CORE_PEER_LOCALMSPID=RegionalOfficeMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/regionaloffice.example.com/peers/peer0.regionaloffice.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/regionaloffice.example.com/peers/peer0.regionaloffice.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.regionaloffice.example.com:/var/hyperledger/production
    ports:
      - 9051:9051
      
  caDGCAOffice:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-dgcaoffice
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.dgcaoffice.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.dgcaoffice.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/dgcaoffice.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      
  caRegionalOffice:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-regionaloffice
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.regionaloffice.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.regionaloffice.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/regionaloffice.example.com/ca/:/etc/hyperledger/fabric-ca-server-config